addSbtPlugin("se.marcuslonnberg" % "sbt-docker"           % "1.5.0")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"         % "0.14.6")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"         % "1.4.0")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"          % "0.3.4")
addSbtPlugin("net.virtual-void"  % "sbt-dependency-graph" % "0.9.2")
addSbtPlugin("io.spray"          % "sbt-revolver"         % "0.9.1")
