addSbtPlugin("org.wartremover"   % "sbt-wartremover" % "2.3.0")
addSbtPlugin("se.marcuslonnberg" % "sbt-docker"      % "1.5.0")
addSbtPlugin("com.eed3si9n"      % "sbt-assembly"    % "0.14.6")
addSbtPlugin("com.geirsson"      % "sbt-scalafmt"    % "1.4.0")
addSbtPlugin("com.timushev.sbt"  % "sbt-updates"     % "0.3.4")
